replicaCount: 2

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fastapi-study.cseteram.dev
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
